# Put system-specific overrides into: ~/.tmux.local.conf

# NOTE - on older systems, use screen-256color
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB,*256col*:RGB"

set -g history-limit 20000

set -g prefix C-a
bind C-a send-prefix
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# "C-a r" will reload the configs
bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"

bind Tab last-pane

set -g status-bg colour2
set -g status-fg colour0
set -g status-justify centre
set -g status-keys vi

set -g mouse on

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows off  # Keep stable numeration of windows

set -g display-panes-time 3000
set -g display-time 5000

set -g window-status-separator " | "
set -g window-status-current-style "bg=colour228 fg=black"
set -g window-status-format " #I. #W#F "
set -g window-status-current-format " #I. #W #F "

set -g status-left "#[fg=yellow,bg=black] #S  #[fg=colour239]#H  "
set -g status-left-length 25
set -g status-right "#[bg=black]  #[fg=white]%H:%M  #[fg=colour239]%Y-%m-%d  "
set -g status-right-length 25

set-window-option -g pane-border-style fg=colour239
set-window-option -g aggressive-resize on

set -g focus-events on
set -sg escape-time 10

source-file -q ~/.tmux.local.conf
